name: test
on: [push]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://buildkite/puppeteer
      - name: Install
        run: yarn
      - name: Test
        run: yarn test
